apiVersion: v2
name: sa-platform
description: Plataforma de microservicios de veterinaria para la Practica 6 en Kubernetes administrado.
type: application
version: 0.1.0
appVersion: "1.0.0"
icon: https://helm.sh/img/helm.svg
dependencies:
  - name: api-gateway
    version: 0.1.0
    repository: file://charts/api-gateway
    condition: services.apiGateway.enabled
  - name: owners-service
    version: 0.1.0
    repository: file://charts/owners-service
    condition: services.owners.enabled
  - name: pets-service
    version: 0.1.0
    repository: file://charts/pets-service
    condition: services.pets.enabled
  - name: appointments-service
    version: 0.1.0
    repository: file://charts/appointments-service
    condition: services.appointments.enabled
  - name: medical-records-service
    version: 0.1.0
    repository: file://charts/medical-records-service
    condition: services.medicalRecords.enabled
  - name: auth-service
    version: 0.1.0
    repository: file://charts/auth-service
    condition: services.auth.enabled
  - name: authorization-service
    version: 0.1.0
    repository: file://charts/authorization-service
    condition: services.authorization.enabled
  - name: postgresql
    version: 15.5.38
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: rabbitmq
    version: 14.6.6
    repository: https://charts.bitnami.com/bitnami
    condition: rabbitmq.enabled
