global:
  logLevel: debug

services:
  apiGateway:
    replicas: 2
    image:
      tag: "0.1.0"
  owners:
    replicas: 2
    image:
      tag: "0.1.0"
  pets:
    replicas: 2
    image:
      tag: "0.1.0"
  appointments:
    replicas: 2
    image:
      tag: "0.1.0"
  medicalRecords:
    replicas: 2
    image:
      tag: "0.1.0"
