{{- if .Values.resourceQuota.enabled }}
apiVersion: v1
kind: ResourceQuota
metadata:
  name: sa-platform-quota
  namespace: {{ .Values.namespace.name | quote }}
spec:
  hard:
    {{- toYaml .Values.resourceQuota.hard | nindent 4 }}
---
{{- end }}
{{- if .Values.limitRange.enabled }}
apiVersion: v1
kind: LimitRange
metadata:
  name: sa-platform-limits
  namespace: {{ .Values.namespace.name | quote }}
spec:
  limits:
    - type: Container
      default:
        {{- toYaml .Values.limitRange.default | nindent 8 }}
      defaultRequest:
        {{- toYaml .Values.limitRange.defaultRequest | nindent 8 }}
{{- end }}

