apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sa-platform-p8
  namespace: argocd
spec:
  project: sa-platform-p8
  source:
    repoURL: https://github.com/yaniadavid/Practicas-SA-B-202010175-P8.git
    targetRevision: main
    path: charts/sa-platform
    helm:
      valueFiles:
        - ../../apps/sa-platform/values-p8.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: sa-p8
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false

