apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: p8-disallow-latest-tag
spec:
  validationFailureAction: Enforce
  background: true
  rules:
    - name: require-versioned-image-tag
      match:
        any:
          - resources:
              kinds:
                - Pod
      validate:
        message: "Las imagenes no pueden usar latest."
        pattern:
          spec:
            containers:
              - image: "!*:latest"

