apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: sa-platform-secret
  namespace: sa-p8
spec:
  encryptedData:
    SUPABASE_URL: AgByExampleEncryptedValue
    SUPABASE_SERVICE_ROLE_KEY: AgByExampleEncryptedValue
    AES_SECRET_KEY: AgByExampleEncryptedValue
    EMAIL_HASH_SECRET: AgByExampleEncryptedValue
    JWT_SECRET: AgByExampleEncryptedValue
    postgres-password: AgByExampleEncryptedValue
    rabbitmq-password: AgByExampleEncryptedValue
  template:
    metadata:
      name: sa-platform-secret
      namespace: sa-p8
    type: Opaque
